### ISSUE TITLE
#1 Task

### ISSUE THREAD

**Issue by DmitrySharikov** [mrpeje/Blog#1]
* https://github.com/plataformatec/devise при помощи этой библиотеки запили регистрацию юзеров.
* Запили апдейт постов и разреши его делать только зарегистрированным юзерам
* https://github.com/twbs/bootstrap-sass при помощи этой библиотеки ты сможешь подключить модный фреймворк, который позволит тебе без лишних телодвижений сверстать более-менее красивую страничку. Это и будет твоим заданием: запили header и сверстай нормально страницу для отображения всех постов. (http://getbootstrap.com/components/ здесь можно подсмотреть примеры)

**Comment by jFoxSingularity** [comment]
Не используй гемы для бутстрапа.
Не используй локальные файлы для бутстрапа.

С учётом области покрытия планеты интернетом - Bootstrap CDN для этих нужд более чем достаточно.

Однако стоит заметить что CSS-файлы должны подключаться в *header*'е, а вот js-ки в *footer*'e

**Comment by DmitrySharikov** [comment]
@jFoxSingularity назови три причины почему нельзя использовать гемы для бутстрапа?
> Однако стоит заметить что CSS-файлы должны подключаться в header'е, а вот js-ки в footer'e
не понял, что ты имел ввиду, но разумнее это делать в соответствующих макетам application.js и application.css

**Comment by mrpeje** [comment]
Один даёт чёткие коментарии и таски, другой говорит не используй то, не используй это и в придачу даёт какие то не понятные и абстрактные дерективы со своим особенным сленгом.
Хмммм...кого же послушать?

**Comment by DmitrySharikov** [comment]
@mrpeje ну вот когда у твоего блога будет трафик хотя бы 1гб в день, тогда и подключишь CDN, а так, это что мертвому припарка

**Comment by jFoxSingularity** [comment]
Куда уж понятнее?

CDN нужно использовать везде и всегда. Куда понятнее написать про хэдер и футер - не знаю)
Если у пользователя отключён js в браузере, не разумнее было бы его вынести вниз?

**Comment by DmitrySharikov** [comment]
@jFoxSingularity ты так и не назвал три причины. И незачем использовать CDN, если:
* Это блог
* Пользователи не по всему миру и нет большого трафика.

Да и вообще, почему ты не придрался к тому, что блог написан на рельсах, если есть sinatra/jekyll/%любой_другой_фрэйм_без_mvc_модели%? Правильно, человек просто желает научиться пользоваться фреймворком и твои советы здесь просто не к месту :shipit:
